@baseUrl = http://localhost:8080
@email = test@test.com
@password = test1234
@nickname = 방토

### 게시판 신청
POST {{baseUrl}}/api/board-applications
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "귀멸의 칼날",
  "description": "귀멸의 칼날 이야기를 하는 게시판입니다."
}

### 내 게시판 신청 조회
GET {{baseUrl}}/api/me/board-applications
Authorization: Bearer {{accessToken}}